### ISSUE TITLE
Initializing repo checklist

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/eligibility-server#1]
- Be able to build container, run container
- Be able to launch app in Debug mode in Devcontainer

### Required
- [x] README
- [x] LICENSE
- [x] .gitignore

### Python
- [x] requirements.txt
- [x] app.py (transfer all files)
- [x] .pyup.yml
- [x] pyproject.toml

### Docker
- [x] Dockerfile
- [x] Docker Compose file
- [x] .devcontainer
- [x] .vscode/launch.json (for Dev Container debugging)
