### ISSUE TITLE
Make Release: 2022.11.1

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#191]
### Release manager

@angela-tran 

### Release version

2022.11.1

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge #190 
- [x] (If applicable): open another PR from dev to test #188 
- [x] QA the app in test @angela-tran  (`/healthcheck` and other endpoints)
- [x] Open a PR to for the test branch into prod, merge #192
- [x] QA the app in prod
   - Had to manually apply for now due to a 403 error in the pipeline
   - Fixed #197 
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
Drafted release notes:

## Overview
This is the initial release and contains:
* A server implementation of the Eligibility Verification API, with support for
   * Hashing inputs
   * Importing CSV or JSON data
* Unit tests
* Devcontainer / GitHub Actions configuration
* Infrastructure-as-code using Terraform for deployment to Azure
* Azure pipeline to apply infrastructure changes as CI/CD

## What's Changed
* Initialize app + Transfer code by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/2
* Configure pytest and test healthcheck by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/11
* README link to API spec by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/17
* Add GitHub Action for pre-commit by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/14
* Refactor app into eligibility_server/app by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/19
* Enable dynamic localhost ports by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/20
* Update devcontainer name by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/23
* GitHub Action that builds and publishes to GitHub Container Registry by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/22
* Add basic unit tests and unit test running action by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/16
* Remove Merchant mocked data, methods by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/31
* Add docs and GitHub Action to publish docs by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/24
* Update link and test command by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/36
* Create Database, Verify classes by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/32
* Move server config to settings by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/33
* Upgrade Flask, Flask-REST by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/37
* Upgrade jwcrypto and cryptography by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/39
* Docs deploy GitHub Action *paths* filter by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/41
* Set up Dependabot by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/43
* chore(deps): (deps): bump pre-commit/action from 2.0.0 to 2.0.3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/44
* Remove redundant (deps) by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/45
* Pin conventional-precommit by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/47
* Remove specification files that have been moved to 'eligibility-api' project by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/49
* chore (deps): bump cryptography from 35.0.0 to 36.0.0 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/50
* chore (deps): bump cryptography from 36.0.0 to 36.0.1 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/52
* chore: configure vscode test debugging by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/53
* Refactor check_user to optionally hash key and user inputs by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/51
* Chore: use immutable tag reference by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/56
* Add settings test by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/55
* Feature: Add CSV compatibility to Database by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/58
* Refactor scripts by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/60
* chore(deps): bump actions/checkout from 2 to 3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/65
* chore(deps): bump actions/setup-python from 2 to 3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/64
* chore (deps): bump flask from 2.0.2 to 2.0.3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/61
* fix(pre-commit): update black by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/82
* chore(deps): bump actions/setup-python from 2 to 3.1.1 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/72
* chore(deps): bump docker/login-action from 1 to 2 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/78
* chore(deps): bump docker/build-push-action from 2 to 3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/79
* chore (deps): bump cryptography from 36.0.1 to 37.0.2 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/77
* chore (deps): bump jwcrypto from 1.0 to 1.3.1 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/81
* CI: add issues and Dependabot PRs to Project Board by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/87
* Feat: add CODEOWNERS file by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/89
* fix(Dockerfile): add build-essential, so that pre-commit can be installed by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/85
* Docs: Update docs to reflect new server features by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/90
* chore (deps): bump flask from 2.0.3 to 2.1.2 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/76
* Add CodeQL security analysis for pull requests by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/93
* Move Docker files into .devcontainer by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/94
* chore(deps): bump pre-commit/action from 2.0.3 to 3.0.0 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/95
* chore(deps): bump actions/setup-python from 3 to 4 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/96
* chore (deps): bump cryptography from 37.0.2 to 37.0.4 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/97
* chore (deps): bump flask from 2.1.2 to 2.1.3 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/98
* Feat: import user data on server container startup by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/101
* Feat: configurable sub format by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/99
* Fix: idempotent setup and teardown by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/104
* CSV configuration variables by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/105
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/cal-itp/eligibility-server/pull/115
* chore (deps): bump flask from 2.1.3 to 2.2.2 by @dependabot in https://github.com/cal-itp/eligibility-server/pull/118
* Add GitLens and Git Graph extensions by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/117
* Refactor: Add logging by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/116
* Feat: upgrade to Python 3.10 by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/120
* Use Flask configuration framework by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/119
* Chore: devcontainer setup by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/126
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/cal-itp/eligibility-server/pull/133
* Chore: fix CI commit format by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/134
* Refactor: Database class - remove in-memory data by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/132
* Feat: production container by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/123
* Configurable log level, plus settings documentation by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/128
* Fix: correct subdirectory copying in Dockerfile by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/138
* Raise JSON errors, add app error handling methods and test by @machikoyasuda in https://github.com/cal-itp/eligibility-server/pull/129
* Feat: configurable keypair via settings by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/136
* Chore: specify 8000 as port in launch.json by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/141
* chore(pre-commit): autoupdate hooks by @pre-commit-ci in https://github.com/cal-itp/eligibility-server/pull/145
* Fix: configure root logger by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/146
* Refactor: organize application as a package by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/140
* Feat: settings/configuration helper by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/144
* Chore: build script for docker images by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/149
* Refactor: models by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/148
* Feat: load remote data by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/151
* chore(pre-commit): autoupdate hooks by @pre-commit-ci in https://github.com/cal-itp/eligibility-server/pull/154
* Refactor sample data by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/156
* fix link to API spec by @afeld in https://github.com/cal-itp/eligibility-server/pull/159
* chore(pre-commit): autoupdate hooks by @pre-commit-ci in https://github.com/cal-itp/eligibility-server/pull/161
* Chore: more realistic sample data by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/165
* Refactor: separate environments by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/169
* Feat: terraform by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/166
* ignore hidden-link tags created by Azure on the App Service by @afeld in https://github.com/cal-itp/eligibility-server/pull/171
* ci: deploy to test and prod environments by @afeld in https://github.com/cal-itp/eligibility-server/pull/173
* fix workspace selection in pipeline by @afeld in https://github.com/cal-itp/eligibility-server/pull/175
* fix(pipeline): use different variable to support deployment from dev, test, or prod branches by @afeld in https://github.com/cal-itp/eligibility-server/pull/177
* Fix: use runtime expression syntax for variables by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/178
* Fix: use runtime expression syntax for variables (with correct syntax) by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/179
* Fix: pre-commit default_stages to avoid duplicate hook runs by @thekaveman in https://github.com/cal-itp/eligibility-server/pull/167
* Chore(pipeline): clean up debug message by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/180
* Terraform: define variable-driven IP address restrictions by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/181
* docs(Terraform): add more details around variables by @afeld in https://github.com/cal-itp/eligibility-server/pull/183
* Chore: merge main into dev by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/186
* Chore: remove fake delay by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/187
* chore(Azure): split the Key Vault access for engineers from that for the deployer by @afeld in https://github.com/cal-itp/eligibility-server/pull/185
* Prep release 2022.11.1 by @angela-tran in https://github.com/cal-itp/eligibility-server/pull/190
* fix(pipeline): use default workspace for prod by @afeld in https://github.com/cal-itp/eligibility-server/pull/194

**Full Changelog**: https://github.com/cal-itp/eligibility-server/commits/2022.11.1
