### ISSUE TITLE
Configure Sentry for error monitoring

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#252]
Corollary to cal-itp/benefits#1258

## Acceptance Criteria

- [ ] Application errors are being collected by Sentry

## Tasks

- [x] Create a Project for Eligibility Server (assign to the Benefits team in Sentry)
- [x] Set up the SDK
- [x] Set the environment variables
  - [x] Dev
  - [x] Test
  - [x] Prod
- [x] Ensure we can distinguish which [environment](https://docs.sentry.io/product/sentry-basics/environments/) errors are coming from
- [x] Update docs
- [x] Configurable `traces_sample_rate` parameter with a lower default
- [x] Setting for `SENTRY_DSN`

## Follow-up (after merge)

- [ ] Set up GitHub integration for issues
- [ ] Ensure notifications are sent to Slack

## Additional Context

Sentry has a built-in Flask project type to start from: 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1783439/231810938-955231f9-9665-4e81-b15c-a85aa439df8b.png">

**Comment by angela-tran** [comment]
Re: these items from the issue description,

> - [ ] Send notifications to Slack
> - [ ] Set up GitHub integration

### GitHub
I tried to set up [GitHub integration](https://docs.sentry.io/product/integrations/source-code-mgmt/github/) for the `eligibility-server` Sentry project, but I don't have enough permissions. @thekaveman Maybe this is something you have enough permissions to do?

> Sentry owner, manager, or admin permissions, and GitHub owner permissions are required to install this integration.

### Slack
I've set up the Alert rule for the `eligibility-server` Sentry project to send Slack notifications, but haven't been able to trigger it. The `benefits` Sentry project also hasn't triggered its Slack alert since 14 days ago, which tells me this is not specific to `eligibility-server`.

**Comment by thekaveman** [comment]
@angela-tran I moved those additional items (Slack, GitHub) to follow-up so we're not blocked on getting this in. 

I do have a few comments on the PR that need to be addressed before we can merge.
