### ISSUE TITLE
Make a release: 2023.06.1

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#268]
### Release manager

@thekaveman

### Release version

2023.06.1

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into dev, merge #270
- [x] Open another PR from dev to test, merge #271
- [x] QA the app in test 👍 
- [x] Open a PR to for the test branch into prod, merge #273 
- [x] QA the app in prod 👍 
- [x] Tag the release on the prod branch, push the tag to GitHub 
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed
